version: '3'

services:
  mysql:
    image: mysql:5.7
    networks:
      - production-network
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mercado-livre

  mercado-livre:
    build:
      dockerfile: ./Dockerfile
      context: .
    image: thalyta-mercado-livre
    environment:
      DB_URL: jdbc:mysql://mysql/mercado-livre
      DB_USER: root
      DB_PASSWORD: password

    restart: always
    ports:
      - "3000:8080"
    networks:
      - production-network
    depends_on:
      - mysql


networks:
  production-network:
    driver: bridge